### PR TITLE
Fix issue #36 and expose the source_ami_owner variable to the make fi…

### PR DESCRIPTION
**Pull request by leonli**
Fix issue #36, tested on eks version 1.19 and 1.21, and expose the source_ami_owner variable, so that the repo can be used for different regions

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ygoodmn** [comment]
Thanks for the fix, will it be merged ?

For version 1.18, I am getting a warning on the stop docker, is that expected ? PSB

1628751328,,ui,message,    amazon-ebs: + echo EnvironmentFile=/etc/environment
1628751328,,ui,message,    amazon-ebs: + echo 'stop docker'
1628751328,,ui,message,    amazon-ebs: stop docker
1628751328,,ui,message,    amazon-ebs: + systemctl stop docker
1628751328,,ui,message,    amazon-ebs: Warning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
1628751328,,ui,message,    amazon-ebs: + echo 'rebooting the instance'
1628751328,,ui,message,    amazon-ebs: rebooting the instance
1628751328,,ui,message,    amazon-ebs: + reboot

**Comment by nmarchini** [comment]
can this get reviewed and merged please as no AMIs start correctly on AWS without it

**Comment by bryantbiggs** [comment]
closed in #57

**Comment by nmarchini** [comment]
Thanks. Shame it took 12 months to fix.

**Pull request closed without merging**
